private_message_index:
    path: /private_message
    defaults: { _controller: AppBundle:PrivateMessage:index }
    
private_message_sended:
    path: /private_sended
    defaults: { _controller: AppBundle:PrivateMessage:sended }
    
private_message_notification:
    path: /private_message/notification/get
    defaults: { _controller: AppBundle:PrivateMessage:notReaded }